### ISSUE TITLE
Mod not working at all

### ISSUE THREAD

**Issue by DeadKper** [florensie/no-weak-attack#1]
I'm on linux using java 8, mc version is 1.16.5, fabric loader v 0.11.3 (according to multimc) the only other mod that can use this mechanic is Enhanced Attack Indicator, but it only uses the attack indicator to show the cd on ender pearls, the strength of bow and crossbow and the eating time, unless the mod is incompatible with lithium, viafabric or multiconnect I don't see the reason why is not working, if you need any other information just ask, never have done an issue report before

**Comment by florensie** [comment]
Hey, do you have the latest version of the mod? One of the older versions was broken.

**Comment by DeadKper** [comment]
Yes, the 1.1.2 to be exact

**Comment by florensie** [comment]
Huh, ok I'll have to look into that. Makes no sense though.

**Comment by DeadKper** [comment]
Don't know why it should because java works in a vm for a reason but it's probably something to do with linux, I'm using manjaro architect to be exact, v 1.1.1 of the mod has the same issue, I'll try the other versions and report back if you want, also, I'll try uninstalling all other mods to isolate the problem

**Comment by florensie** [comment]
Don't bother, all versions except the latest are pretty broken. Manjaro shouldn't have anything to do with it because I use arch linux btw.

Are you sure the mod loaded correctly, maybe check the log or post one here?

**Comment by DeadKper** [comment]
Actually, version 1.0.0 is working, the only one working xD, no other mods, I tried all without mods and only the first one is working for some reason, let me install 1.1.2 and check the logs

**Comment by florensie** [comment]
1.0.0 should work but doesn't let you hold your attack button to keep attacking.

**Comment by DeadKper** [comment]
Maybe it was my computer, I reinstalled 1.1.2 and now it's working for some reason (?), I'll try with the mods again to make sure I'm not tripping and wasting your time.

**Comment by DeadKper** [comment]
Sure enough, now it's working, so sorry for wasting your time, would like to let you know if it was my pc or something but I can't tell really
